(*
**
** Based upon RADU source
**
*)

Const
  ralYes      =   1;                                                { Y Yes }
  ralNo       =   2;                                                 { N No }
  ral1AtATime =   3; { Sorry, you may only log on to one line at any one ti }
  ralNotFound1=   4;   { Your name was not located in the system user file. }
  ralNmEntered=   5;                                       { Name entered : }
  ralAskNmOk  =   6;                    { Did you enter your name correctly }
  ralPrivSys  =   7;                       { Sorry, this system is private. }
  ralInvName  =   8;    { Sorry, that name is not acceptable on this system }
  ralAskAnsi  =   9;              { Would you like ANSI colour and graphics }
  ralAskFSed  =  10;       { Do you want to use the ANSI full-screen editor }
  ralAskAvt   =  11;               { Would you like AVATAR codes to be sent }
  ralAskHotKey=  12;                       { Would you like hot-keyed menus }
  ralAskFSview=  13;                   { Use the full screen message viewer }
  ralAskLines =  14; { How many lines does your display have (10-66, 24 rec }
  ralAskPause =  15;       { Would you like to pause after each screen page }
  ralAskClr   =  16;         { Do you want screen clearing codes to be sent }
  ralAskLoc   =  17;                          { Where are you calling from? }
  ralAskVoice =  18;           { Please enter your home/voice phone number: }
  ralAskData  =  19;        { Please enter your business/data phone number: }
  ralAskHandle=  20;                { Enter your handle (RETURN for none) : }
  ralInvHandle=  21; { That name is already being used by another user, or  }
  ralAskBirth =  22;                      { Please enter your date of birth }
  ralInvBirth =  23;                { You must enter a valid date of birth! }
  ralAskPsw1  =  24;                          { Enter your password to use: }
  ralAskPsw2  =  25;                    { Please re-enter for verification: }
  ralInvPsw1  =  26;                              { Passwords do not match! }
  ralAskInfOk =  27;    { Did you enter all the above information correctly }
  ralScanPhone=  28;       { Scanning phone numbers, please wait a moment.. }
  ralInvVoice =  29; { WARNING: Unacceptable voice phone number entered, no }
  ralInvData  =  30; { WARNING: Duplicate voice phone number entered, notif }
  ralTooSlow  =  31; { Sorry, but you cannot use this system at this speed. }
  ralNo300    =  32; { Sorry, 300 baud callers are not permitted to call at }
  ralNoSysop  =  33;          { ** Sysop Remote Access Has Been Disabled ** }
  ralIncPsw   =  34;                                { Incorrect, try again. }
  ralNoAccess =  35;                                       { Access denied! }
  ralAskMsg   =  36;                         { Leave a message to the sysop }
  ralSuspended=  37; { Sorry, but your access to this system has been suspe }
  ralEventIn  =  38;                                      { System event in }
  ralTimeAdj  =  39;                 { your time limit has been adjusted to }
  ralMinutes  =  40;                                              { minutes }
  ralCheckMail=  41;                               { Check for waiting mail }
  ralCheckFile=  42;                                  { Check for new files }
  ralPswExp   =  43;                   { Your current password has expired! }
  ralPswChng1 =  44; { For security purposes, you are required to change yo }
  ralTimesCall=  45;                                       { times you call }
  ralMvName   =  46;                { File to move/copy (wildcards valid):  }
  ralOtherPsw =  47;         { You can't use the same password! Try again.. }
  ralPswShort1=  48;                  { Your password must contain at least }
  ralChars    =  49;                                           { characters }
  ralNotFnd   =  50;                                           { not found! }
  ralFullPath =  51;                              { Full destination path : }
  ralNotOnTop =  52;                  { Can't copy a file on top of itself! }
  ralErrOpen  =  53;                          { Error opening source file.. }
  ralErrCreate=  54;                       { Unable to create target file.. }
  ralErrCopy  =  55;                         { Error occurred during copy.. }
  ralLRRC     =  56;                      { Would you like a return receipt }
  ralKeyWord  =  57;                                  { K (K)eyword in text }
  ralInvChoice=  58;                    { Invalid choice, please try again: }
  ralNrInRange=  59;                   { Please enter a number in the range }
  ralPassword =  60;                                            { Password: }
  ralNumber   =  61;                                              { Number: }
  ralNumEnter =  62;                                     { Number entered : }
  ralCorrect  =  63;                                      { Is this correct }
  ralExceeded =  64; { Sorry, daily time limit exceeded -- call back tomorr }
  ralTimeRem  =  65;                           { WARNING -- Time remaining: }
  ralInactive1=  66;           { * User Inactivity Timeout, Disconnecting * }
  ralInactive2=  67;     { You are about to be disconnected for inactivity! }
  ralMore     =  68;                                     { YN= More(Y/n/=)? }
  ralStartCht =  69;                        { Sysop breaking in for a chat: }
  ralNoUser1  =  70;                                     { No user on-line! }
  ralEndCht   =  71;                                { Sysop chat mode ended }
  ralMoment   =  72;                              { Please wait a moment... }
  ralThanks   =  73;                                  { Thanks for waiting. }
  ralLocOut   =  74;                               { ** LOCKING OUT USER ** }
  ralLocCompl =  75;                     { ** SECURITY LOCK-OUT COMPLETE ** }
  ralErrTop   =  76;                     { Top menu missing, disconnecting. }
  ralErrMnu   =  77;                                { ERROR - Menu missing: }
  ralMsgRange =  78;                     { System contains messages ranging }
  ralDelMsg   =  79;                   { Enter number of message to delete: }
  ralNoMsgNr  =  80;                                { There is no message # }
  ralThisArea =  81;                                         { in this area }
  ralDeleting =  82;                                   { Deleting message # }
  ralErrDel   =  83;                      { You cannot delete that message. }
  ralNoCredits=  84; { Sorry, you do not have sufficient credit for this de }
  ralNoNode   =  85;                                  { Could not find node }
  ralNodelHdr =  86; { ? to list zones, z:? to list nets in zone z, n/? to  }
  ralAvailZone=  87;                                      { Available zones }
  ralNrName   =  88; {           Number  Name                               }
  ralNetsRegs =  89;                                 { Nets/regions in zone }
  ralNodesIn  =  90;                                             { Nodes in }
  ralSorryNo  =  91;                                   { Sorry, there is no }
  ralListed   =  92;                                               { listed }
  ralNoNLhelp =  93;  { Sorry, nodelist help is not available at this time. }
  ralZone     =  94;                                                 { Zone }
  ralRegion   =  95;                                               { Region }
  ralNet      =  96;                                                  { Net }
  ralNode     =  97;                                                 { Node }
  ralChUser   =  98;               { Choose a user (enter the line number): }
  ralNoUser2  =  99;               { Sorry, there isn't anyone on that line }
  ralNoDisturb= 100;                        { doesn't wish to be disturbed. }
  ralSysOverr = 101;                         { Sysop Override : Send anyway }
  ralMsgTo    = 102;                                           { Message to }
  ralNode2    = 103;                                                 { node }
  ralAborted  = 104;                                             { Aborted. }
  ralProcess  = 105;                                        { Processing... }
  ralMsgSent  = 106;                                         { Message sent }
  ralPageHours= 107;      { Sorry, but you may only page for a chat between }
  ralMaxPage1 = 108;                  { Sorry, you may only page for a chat }
  ralMaxPage2 = 109;                                      { times per call. }
  ralAskWhy   = 110;           { Why would you like to chat with the sysop? }
  ralNotAvail = 111;     { Sorry, but the sysop is not currently available. }
  ralLeaveMsg = 112;                         { Leave a message to the sysop }
  ralInvPsw2  = 113; { Sorry, this password is unacceptable. Please try som }
  ralLessSim  = 114; { You must select a password that is less similar to y }
  ralSelDesel = 115; { SDQ Would you like to (S)elect, (D)e-Select all mess }
  ralVerTurn  = 116;       { Verify that you would like to make this change }
  ralON1      = 117;                                                   { ON }
  ralOff      = 118;                                                  { OFF }
  ralLocAttach= 119;                                   { Attach local files }
  ralEntrName = 120; { Enter full path and file names to send, 1 per line ( }
  ralFile1    = 121;                                                { File: }
  ralSent1    = 122;                                                { Sent: }
  ralNotFound2= 123;                                       { Could not find }
  ralTogglArea= 124;                    { Enter message area(s) to toggle : }
  ralNoDataFil= 125;                                { Data file not present }
  ralViewFile = 126;                        { File to view (Enter to quit): }
  ralNoFiles1 = 127;            { Cannot locate any files for this message! }
  ralFilesAtt = 128;                      { Files attached to this message: }
  ralAskMvDir = 129;                          { Directory to move files to: }
  ralMoving   = 130;                                      { Moving files... }
  ralCheckAtt = 131; { Check that you have all the files safely. Okay to ki }
  ralKillAtt  = 132;                        { Killing the attached files... }
  ralAvtAct   = 133;                              { AVATAR codes now active }
  ralAvtInact = 134;                        { AVATAR codes will NOT be used }
  ralCalls2day= 135;                                    { Todays Callers to }
  ralCallsHdr = 136; { Name                Line   BaudRate   LogOn  LogOff  }
  ralQuiet    = 137;                                           { Quiet Mode }
  ralNoFSed   = 138;   { Sorry, but the full screen editor is not installed }
  ralWarnFSed = 139; { WARNING! The full screen editor requires that you ha }
  ralFSedAct  = 140; { The full screen message editor will be used to enter }
  ralFSedInact= 141;       { The line editor will be used to enter messages }
  ralAnsSlow  = 142; { Sorry, ANSI graphics are not available at this speed }
  ralAnsAct   = 143;                      { ANSI/Colour graphics now active }
  ralAnsInact = 144;                { ANSI/Colour graphics will NOT be used }
  ralHotAct   = 145;                                       { HotKeys active }
  ralHotInact = 146;                                     { HotKeys disabled }
  ralPagePause= 147;                                         { Page Pausing }
  ralFSvAct   = 148;                   { Full screen message reader enabled }
  ralFSvInAct = 149;                  { Full screen message reader disabled }
  ralCurrTime = 150;                               { Current time         : }
  ralCuurDate = 151;                               { Current date         : }
  ralConnTime = 152;                               { Connect time         : }
  ralUsedTime = 153;                               { Time used today      : }
  ralRema2day = 154;                               { Time remaining today : }
  ralDailyLm1 = 155;                               { Daily time limit     : }
  ralClrAct   = 156;                      { Screen clear codes WILL be sent }
  ralClrInact = 157;                  { Screen clear codes will NOT be sent }
  ralMidnight = 158;                                             { Midnight }
  ralNoon     = 159;                                                 { Noon }
  ralLine     = 160;                                                 { Line }
  ralPercUsage= 161;                { Percentage of hourly system usage for }
  ralUsrSearch= 162; { Enter Username search string or [Enter] for all user }
  ralUsrLstHdr= 163; { Name                          Location               }
  ralNoSuchUsr= 164;                 { is not a listed user of this system. }
  ralNewLvl   = 165;                    { Enter new user security-level for }
  ralViewName = 166;                                        { File to view: }
  ralInvViewNm= 167;                  { Sorry, couldn't locate that file... }
  ralOnline   = 168;                                   { Callers On-Line to }
  ralOnlineHdr= 169; { Name                         Line   BaudRate   Statu }
  ralBrowsing = 170;                                             { Browsing }
  ralXFer     = 171;                                            { File Xfer }
  ralMessages1= 172;                                             { Messages }
  ralDoor     = 173;                                                 { Door }
  ralSysopChat= 174;                                           { Sysop Chat }
  ralQuestnr  = 175;                                          { Quest'naire }
  ralDrivSpace= 176;                                        { Drive Space : }
  ralBytes    = 177;                                                { bytes }
  ralProtocol1= 178;                                        { Protocol    : }
  ralNoSpace  = 179;      { There is not enough free space for your upload! }
  ralStartUL  = 180; { Start sending now, or press <Ctrl-X> several times t }
  ralFileUpl  = 181;                                     { File to upload : }
  ralInvUpl   = 182;              { Sorry, but you may not upload that file }
  ralExists1  = 183;                { Sorry, that file already exists here. }
  ralFilesRec = 184;                                       { Files Received }
  ralFileRec  = 185;                                        { File Received }
  ralNoRec    = 186;                                    { No Files Received }
  ralGranted  = 187;                       { You have been granted an extra }
  ralRejected1= 188; { NOTE - One or more of your files was rejected becaus }
  ralRejected2= 189; { NOTE - One or more of your files was rejected becaus }
  ralDescr    = 190; { Begin description with a "/" if file is for the syso }
  ralPlsDesc  = 191;                                      { Please describe }
  ralXferSlow = 192; { Sorry, file transfers are not permitted at this spee }
  ralDownFiles= 193;                                { File(s) to Download : }
  ralNoBatch  = 194; { Sorry, but the protocol you have selected does not s }
  ralTimeLm   = 195;                                     { daily time limit }
  ralExceed   = 196;           { Sorry, but this download would exceed your }
  ralDailyLm2 = 197;                                        { k daily limit }
  ralRatioLm  = 198;                                          { ratio limit }
  ralStrtAbr  = 199; { SLNA (S)tart transfer, (L)ogoff after transfer, (N)e }
  ralXferFiles= 200;                                  { Files To Transfer : }
  ralXferSize = 201;                                  { Transfer Size     : }
  ralXferTime = 202;                                  { Transfer Time     : }
  ralMinsAt   = 203;                                           { minutes at }
  ralBaud     = 204;                                                 { Baud }
  ralStartRecv= 205; { Start receiving now, or press <Ctrl-X> several times }
  ralFilesSent= 206;                                           { Files Sent }
  ralFileSent = 207;                                            { File Sent }
  ralNoSent   = 208;                                        { No Files Sent }
  ralAutoLogof= 209; { Auto logoff in ten seconds : Press "!" to disconnect }
  ralDlFull   = 210;                { File to Download (Full Path & Name) : }
  ralNoFiles  = 211;                                    { No files to send! }
  ralOnlyIntr = 212; { Sorry, only the first six listed protocols are avail }
  ralOneMoment= 213;                                       { One moment ... }
  ralAstrBatch= 214;               { (*) indicates batch transfer available }
  ralProtocol2= 215;                           { Protocol (Return to Quit): }
  ralFreeDl   = 216;                                               { (FREE) }
  ralIncorrect= 217;                                            { Incorrect }
  ralAccepted = 218;                                             { Accepted }
  ralDlTime   = 219;            { Sorry, downloads are only allowed between }
  ralNLbrowse = 220;            { * NODELIST BROWSING * (blank line quits): }
  ralListZones= 221;                                  { ? to list all zones }
  ralListNets = 222;                           { z:? to list nets in zone z }
  ralListNodes= 223;                           { n/? to list nodes in net n }
  ralPswChng2 = 224;                           { Password change successful }
  ralPswShort2= 225;                  { Your password must contain at least }
  ralTryAgain = 226;                              { characters! Try again.. }
  ralBothNames= 227;       { You must enter both your first and last names! }
  ralScrChange= 228;                             { Screen length changed to }
  ralFileAreas= 229;                                          { File Areas: }
  ralMsgAreas = 230;                                       { Message Areas: }
  ralInvArea  = 231;                            { That area does not exist! }
  ralCombined = 232;                                             { Combined }
  ralPattern  = 233;         { File name pattern match (CR for all files) : }
  ralFileHdr  = 234;                      { File Name      Size        Date }
  ralfiles1   = 235;                                                { files }
  ralSelArea  = 236;                                         { Select area: }
  ralKeyw     = 237;                    { Enter keyword to use for search : }
  ralSrcKeyw  = 238;                              { File Search by Keyword; }
  ralPauseStop= 239;                          { Press P to Pause, S to Stop }
  ralSrcAbrt  = 240;           { Search Config File not installed, aborting }
  ralWildcard = 241;       { Enter the file name to find (wildcards valid): }
  ralSrcName  = 242;                                 { File Search by Name; }
  ralArc2View = 243;                                     { Archive to view: }
  ralInvArc   = 244;                                { Unknown archive type! }
  ralArcList  = 245;                                   { Listing of archive }
  ralArcLstHdr= 246; { Filename      Original Size     Ratio Date      Time }
  ralMissing  = 247;                                              { MISSING }
  ralSinceLast= 248;            { Search for files new since your last call }
  ralNewerThan= 249;                            { Show all files newer than }
  ralSrcByDate= 250;                                 { File Search by Date; }
  ralSunday   = 251;                                               { Sunday }
  ralMonday   = 252;                                               { Monday }
  ralTuesday  = 253;                                              { Tuesday }
  ralWednesday= 254;                                            { Wednesday }
  ralThursday = 255;                                             { Thursday }
  ralFriday   = 256;                                               { Friday }
  ralSaturday = 257;                                             { Saturday }
  ralRtnCont  = 258;                          { Press (RETURN) to continue: }
  ralChkMail  = 259;                           { Checking your mail-box ... }
  ralNoNewMail= 260;               { You have no new mail in your mail-box. }
  ralNewMail  = 261;                         { You have the following mail: }
  ralMessage  = 262;                                              { message }
  ralmessages2= 263;                                             { messages }
  ralRead     = 264;                                               { R Read }
  ralScan     = 265;                                          { S Scan mail }
  ralQuickScan= 266;                                     { Q Quickscan mail }
  ralKilling  = 267;                                   { K Killing mail ... }
  ralMarking  = 268;                            { M Marking as received ... }
  ralHelp1    = 269;                                                 { Help }
  ralReadNow  = 270;                { Would you like to read this mail now? }
  ralSureKill = 271; { Are you sure you wish to kill all mail addressed to  }
  ralNoMsgTxt = 272;                            { There is no message text! }
  ralDelStart = 273;                            { Delete starting at line # }
  ralDelEnd   = 274;                            { Delete ending   at line # }
  ralEditLine1= 275;                                 { Enter line # to edit }
  ralMaxLen   = 276;                             { Maximum length exceeded! }
  ralInsLine  = 277;               { Enter line # to insert new text before }
  ralAdjLine  = 278;                               { Enter line # to adjust }
  ralCurrLine = 279;                                { Line currently reads: }
  ralReplWhat = 280;                                   { Text to replace  : }
  ralReplWith = 281;                                   { Replacement text : }
  ralNowReads = 282;                                      { Line now reads: }
  ralBeginMsg = 283; { Begin your message now. Words are wrapped automatica }
  ralMaxOf    = 284;                                           { Maximum of }
  ralLines    = 285;                                                { lines }
  ralChrPerLn = 286;                                  { characters per line }
  ralFuncAvail= 287;                                 { Functions available: }
  ralLinesTxt = 288;                                        { lines in text }
  ralDelete1  = 289;                                             { D Delete }
  ralEditLine2= 290;                                          { E Edit line }
  ralReplace  = 291;                                            { R Replace }
  ralInsert   = 292;                                             { I Insert }
  ralHelp2    = 293;                                               { H Help }
  ralContinue = 294;                                           { C Continue }
  ralList     = 295;                                          { L List text }
  ralSave     = 296;                                               { S Save }
  ralQuit1    = 297;                                               { Q Quit }
  ralSelect   = 298;                                              { Select: }
  ralSure     = 299;                                         { Are you sure }
  ralAttFiles1= 300;                         { Send files with this message }
  ralSaving   = 301;                           { Saving message to disk ... }
  ralSubject1 = 302;                                            { Subject : }
  ralName2Use = 303;                              { Enter the name to use : }
  ralVeriUser = 304;                                   { Verifying user ... }
  ralInvAlias = 305;                   { You can't use another user's name! }
  ralTryOther = 306;                 { You can't use that name, try another }
  ralTo1      = 307;                                            { To      : }
  ralInvAskBrw= 308; { That is not a valid user of this system. Browse the  }
  ralNotSysop = 309; { You can't post a message to SYSOP in an EchoMail con }
  ralAddress  = 310;                                            { Address : }
  ralFwardArea= 311;                          { Area to forward message in: }
  ralPostIn   = 312;                             { Area to post message in: }
  ralNetReply = 313;                           { Reply via personal NetMail }
  ralNoWrite  = 314; { You are not permitted to post messages in this area. }
  ralInsCred  = 315; { Sorry, you do not have sufficient credit for this de }
  ralFwarding = 316;                              { Forwarding message from }
  ralReplying = 317;                               { Replying to message in }
  ralPosting  = 318;                                   { Posting message in }
  ralArea     = 319;                                                 { area }
  ralScanUsers= 320;                               { Scanning user-file ... }
  ralUseAlias = 321;                                         { Use an alias }
  ralFrom1    = 322;                                            { From    : }
  ralon2      = 323;                                                   { on }
  ralSubject2 = 324;                                            { Subject : }
  ralAskChange= 325;                                      { Change anything }
  ralSubAb    = 326;   { SA (S)ubject, or (A)bort message, (Enter)=Nothing: }
  ralToName1  = 327;                                         { T (T)o name, }
  ralChngWhat = 328;                          { What do you want to change? }
  ralToName2  = 329;                                              { To name }
  ralSubjName = 330;                                         { Subject name }
  ralAbort    = 331;                                                { Abort }
  ralPrivate1 = 332;                                              { Private }
  ralAskDelSnt= 333;             { Delete message after sent to destination }
  ralAskCrash = 334;                   { Send message with 'crash' priority }
  ralAskAttach= 335;                            { Attach files with message }
  ralAskAttFls= 336;                                   { File(s) to attach: }
  ralAskQuote = 337;                     { Quote text from original message }
  ralQuoting  = 338;                               { Quoting reply text ... }
  ralUplPrep  = 339;                            { Upload a prepared message }
  ralMsgAbort = 340;                                     { Message aborted. }
  ralTooLarge = 341;                    { Message larger than 20k, aborted. }
  ralErrFSed  = 342;          { Error in executing external message editor. }
  ralInactive3= 343;                                 { Inactivity time-out. }
  ralDeleted1 = 344;                                            { (DELETED) }
  ralPrivate2 = 345;                                            { (PRIVATE) }
  ralReceived1= 346;                                           { (RECEIVED) }
  ralFileAtt1 = 347;                                        { (FILE ATTACH) }
  ralKillSent1= 348;                                          { (KILL/SENT) }
  ralSent2    = 349;                                               { (SENT) }
  ralCrash1   = 350;                                              { (CRASH) }
  ralReqRec1  = 351;                                        { (REQ RECEIPT) }
  ralAuditReq = 352;                                          { (AUDIT REQ) }
  ralRetRec1  = 353;                                     { (RETURN RECEIPT) }
  ralFrom2    = 354;                                            {    From : }
  ralTo2      = 355;                                            {      To : }
  ralSubject3 = 356;                                            { Subject : }
  ralAttFiles2= 357; { There are files attached to this message; Press (F)  }
  ralEnclosed = 358;                                           { Enclosed : }
  ralReplies  = 359;                                            { Replies : }
  ralDt       = 360;                                                  { Dt: }
  ralBy       = 361;                                                  { By: }
  ralTo3      = 362;                                                  { To: }
  ralRe       = 363;                                                  { Re: }
  ralQuickHdr = 364; { #     From                     To                    }
  ralMsgArea  = 365;                                         { Message area }
  ralContains = 366;                                             { contains }
  ralNr2Read  = 367;                       { Enter message number to read : }
  ralMsgStart = 368; { Enter message number to start at (Enter=First/Last): }
  ralPause    = 369;                             { Pause after each message }
  ralMark     = 370;                      { Mark messages for later reading }
  ralClrMark  = 371;                      { Clear currently marked messages }
  ralAskMark  = 372;                    { Mark this message? (yes/No/stop): }
  ralEndMsgs  = 373;                                      { End of messages }
  ralEndNewMsg= 374;                                      { End of new mail }
  ralNoMsgs   = 375;                   { There are no messages in this area }
  ralNoReadAcc= 376;    { You do not have read access to this message area. }
  ralExpName  = 377;                   { Device/filename to export file to: }
  ralCreaErr  = 378;                                  { Cannot create file! }
  ralExporting= 379;                                        { Exporting ... }
  ralDate     = 380;                                            {    Date : }
  ralLocal1   = 381;                                                { Local }
  ralNetmail1 = 382;                                              { NetMail }
  ralEchomail = 383;                                             { EchoMail }
  ralJan      = 384;                                                  { Jan }
  ralFeb      = 385;                                                  { Feb }
  ralMar      = 386;                                                  { Mar }
  ralApr      = 387;                                                  { Apr }
  ralMay      = 388;                                                  { May }
  ralJun      = 389;                                                  { Jun }
  ralJul      = 390;                                                  { Jul }
  ralAug      = 391;                                                  { Aug }
  ralSep      = 392;                                                  { Sep }
  ralOct      = 393;                                                  { Oct }
  ralNov      = 394;                                                  { Nov }
  ralDec      = 395;                                                  { Dec }
  ralToglAttr = 396;                           { Toggle message attributes: }
  ralSelAttr  = 397;                          { Select attribute to toggle: }
  ralNetmail2 = 398;                                            { (NETMAIL) }
  ralLocal2   = 399;                                              { (LOCAL) }
  ralSysAdjMnu= 400;                        { SYSOP Message Adjustment Menu }
  ralNetMsgNr = 401;                                  { New message area: # }
  ralAreaNr   = 402;                                     {  .. Area no.   : }
  ralFrom3    = 403;                                     {  .. From       : }
  ralTo4      = 404;                                     {  .. To         : }
  ralSubject4 = 405;                                     {  .. Subject    : }
  ralAttr     = 406;                                     {  .. Attributes : }
  ralExported1= 407;                                     {  .. Exported   : }
  ralExtAttr  = 408;                                     {  .. Ext Attrib : }
  ralSaveExit = 409;                                   { X .. Save and exit }
  ralQuit2    = 410;                           { Q .. Quit (without saving) }
  ralKillSent2= 411;                                   {  ... Kill/sent   : }
  ralExported2= 412;                                   {  ... Exported    : }
  ralFileAtt2 = 413;                                   {  ... File-attach : }
  ralCrash2   = 414;                                   {  ... Crash       : }
  ralReqRec2  = 415;                                   {  ... Req receipt : }
  ralAudReq   = 416;                                   {  ... Audit req   : }
  ralRetRec2  = 417;                                   {  ... Ret receipt : }
  ralDeleted2 = 418;                                      {  ... Deleted  : }
  ralNetmail3 = 419;                                      {  ... Netmail  : }
  ralPrivate3 = 420;                                      {  ... Private  : }
  ralReceived2= 421;                                      {  ... Received : }
  ralLocal3   = 422;                                      {  ... Local    : }
  ralCurrPsw  = 423;                  { Please enter your current password: }
  ralAgain1   = 424;                                            { A (A)gain }
  ralNext1    = 425;                                             { N (N)ext }
  ralLast1    = 426;                                             { L (L)ast }
  ralReply1   = 427;                                            { R (R)eply }
  ralEnter1   = 428;                                            { E (E)nter }
  ralStop1    = 429;                                             { S (S)top }
  ralDelete2  = 430;                                           { D (D)elete }
  ralFiles2   = 431;                                            { F (F)iles }
  ralReadRepl = 432;                                         { Read Replies }
  ralReadReply= 433;                                           { Read Reply }
  ralAgain2   = 434;                                                { Again }
  ralNext2    = 435;                                                 { Next }
  ralLast2    = 436;                                                 { Last }
  ralDelete3  = 437;                                               { Delete }
  ralReply2   = 438;                                                { Reply }
  ralEnter2   = 439;                                                { Enter }
  ralKludgeTog= 440;                                        { Kludge toggle }
  ralUnreceive= 441;                                            { Unreceive }
  ralUsrSec   = 442;                                               { Usrsec }
  ralExport   = 443;                                               { Export }
  ralForward1 = 444;                                              { Forward }
  ralStop2    = 445;                                               { S Stop }
  ralForward2 = 446;                                          { F (F)orward }
  ralReverse1 = 447;                                          { R (R)everse }
  ralIndivid1 = 448;                                       { I (I)ndividual }
  ralHelp3    = 449;                                             { H (H)elp }
  ralMarked1  = 450;                                           { M (M)arked }
  ralNewMsgs1 = 451;                                         { N (N)ew msgs }
  ralSelected = 452;                                         { S (S)elected }
  ralForward3 = 453;                                              { Forward }
  ralReverse2 = 454;                                              { Reverse }
  ralIndivid2 = 455;                                           { Individual }
  ralMarked2  = 456;                                               { Marked }
  ralNewMsgs2 = 457;                                         { New messages }
  ralQuit3    = 458;                                                 { Quit }
  ralQuit4    = 459;                                             { Q (Q)uit }
  ralSelRead  = 460;                                        { Selected read }
  ralCreteria = 461;            { Read messages according to what criteria: }
  ralFromName1= 462;                                        { F (F)rom name }
  ralToName3  = 463;                                          { T (T)o name }
  ralSubject5 = 464;                                          { S (S)ubject }
  ralQuit5    = 465;                                             { Q (Q)uit }
  ralToName4  = 466;                                              { To name }
  ralToSrc    = 467;                            { Enter 'To' search-string: }
  ralFromName2= 468;                                            { From name }
  ralFromSrc  = 469;                          { Enter 'From' search-string: }
  ralSubject6 = 470;                                              { Subject }
  ralSubjSrc  = 471;                         { Enter subject search-string: }
  ralSlash    = 472;                                                    { / }
  ralLoading  = 473;                               { Loading, one moment... }
  ralUnknArc  = 474;           { Error in archive or unknown archive format }
  ralNoDownAcc= 475;  { You do not have download access for this file area! }
  ralAlreadAtt= 476;                 { File is already attached. Replace it }
  ralDDMMYY   = 477;                                             { DD-MM-YY }
  ralMMDDYY   = 478;                                             { MM-DD-YY }
  ralYYMMDD   = 479;                                             { YY-MM-DD }
  ralDDMmmYY  = 480;                                            { DD-Mmm-YY }
  ralAvailDate= 481;                              { Available date formats: }
  ralNoUpAcc  = 482;    { You do not have upload access for this file area! }
  ralAnsReq   = 483; { WARNING! ANSI graphics are required for the full scr }
  ralForwDis  = 484;                { Automatic message forwarding disabled }
  ralForwEnabl= 485;                 { Automatic message forwarding enabled }
  ralInvUser  = 486;        { User not found. Try again, or (Enter) to quit }
  ralNominate = 487;                { Nominate a user to receive your mail: }
  ralForwFiles= 488; { This message has files attached. Forward them as wel }
  ralNobody   = 489;                                               { Nobody }
  ralLocUpl   = 490;                                        { Local upload. }
  ralExists2  = 491;                       { That file already exists here! }
  ralInvUpload= 492;                       { That file may not be uploaded. }
  ralEncArc   = 493;                    { archive contains encrypted files. }
  ralLocDown  = 494;                                      { Local download. }
  ralErrMove  = 495;                                       { Could not move }
  ralOnNode   = 496;                                              { on node }
  ralMsgFrom  = 497;                                   { ***MESSAGE*** from }
  ralInvDate  = 498; { Invalid date. Please make sure you use the correct f }
  ralReadOnly = 499; { This conference is read-only - you may only use netm }
  ralNoNetRpl = 500; { Original message does not contain sufficient informa }
  ralMsgInUse = 501;                        { Message-base is in use. Retry }
  ralEscCtrlX = 524;                            { ESCAPE or CTRL-X for help }
  ralConf     = 571;                                           { Conference }
  ralHandleO  = 572;                    { Is this a Handles-only conference }
  ralLogingOn = 573;                                           { Logging on }
  ralPassword2= 601;                                           { (Password) }
  ralNotAvail2= 602;                                           { (NotAvail) }
  ralMoreTVE  = 603;              {  YN=TVE More(Y/n/=/(T)ag/(V)iew/(E)dit? }
  ralTagNo    = 604;                                   { TAG file numbers:  }
  ralTagged   = 605;                                             { Tagged:  }
  ralNoTagged1= 606;                                     { No tagged files! }
  ralTaglist  = 607;            { Tagged file list (P to Pause, S to Stop): }
  ralADC      = 608; { ADC (A)dd, (D)elete or (C)lear all entries (Enter to }
  ralDelete   = 609;                                             { Delete:  }
  ralTVE      = 610;        { TVE (Enter) to continue, (T)ag/(V)iew/(E)dit: }
  ralNoTagged2= 611;                 { There are currently no tagged files. }
  ralAddTag   = 612;                  { YNQ Add to tag list (Yes/No/Quit):  }
  ralFilesAdd = 613;                                         { files added. }
  ralATagged  = 614;                                   { is already tagged. }
  ralCTag     = 615;                                       { Clear tag list }
  ralVFPassw  = 616;                             { Validate file passwords: }
  ralDlFD     = 617;                           { Download file descriptions }
  ralNotAvail3= 618;                       { is not available for download. }
  ralCredLim  = 619;                                        { credit limit! }
  ralCost     = 620;                                               { Cost:  }
  ralLocked   = 621;          { is locked, and may not be moved or deleted. }
  ralMCDESQ   = 622; { MCDESQ (M)ove, (C)opy, (D)elete, (E)dit desc, (S)kip }
  ralbaseIUse = 623;                           { File-base is in use. Retry }
  ralPswProtF = 624;                           { Password-protect this file }
  ralExist3   = 625;                   { already exists in the target area! }
  ralTFCDRom  = 626;         { One moment, transferring files from CD-ROM.. }
  ralDC       = 627;      { DC (D)elete or (C)lear all (Enter to continue): }
  ralMsgPosted= 628;             { has just posted a message to you in area }
  ralDefProt  = 629;                                   { Default protocol:  }
  ralSelProt  = 630;        { Select your preferred file transfer protocol: }
  ralSNA      = 631;      { SNA (S)tart transfer, (N)ew protocol, (A)bort:  }
  ralIgnEchoM = 632;           { Echomail in a mailbox scan will be ignored }
  ralDisEchoM = 633;         { Echomail in a mailbox scan will be displayed }
  ralScanUplN = 634;                                { Scan your uploads now }
  ralScanUpl  = 635;                 { Please wait, scanning your uploads.. }
  ralPassed   = 636;                                              { Passed. }
  ralFailViru = 637;                                  { Failed virus check. }
  ralFetchDes = 638;             { One moment, fetching file descriptions.. }
  ralSendCC   = 639;                    { Send carbon copies to other users }
  ralIsAGIF   = 640;                                      { File is a GIF:  }
  ralColours  = 641;                                             { colours. }
  ralNGSC     = 642; { Sorry, but as a GUEST you may not change this settin }
  ralCntSearch= 643;                                  { Continue the search }
  ralInvGrNo  = 644;                                { Invalid group number! }
  ralFleGroup = 645;                                         { File groups: }
  ralSelGroup = 646;                                       { Select group:  }
  ralUnACFILE = 647;                              { Unable to access file:  }
  ralShowEcho = 648;                    { Show EchoMail in a mail-box check }
  ralKeyword2 = 649;                                              { Keyword }
  ralSrchStr  = 650;                   { Enter message text search string:  }
  ralUnKnown  = 651;                                              { Unknown }
  ralMale     = 652;                                                 { Male }
  ralFemale   = 653;                                               { Female }
  ralYourSex  = 654;            { MF What is your sex? (M)ale or (F)emale:  }
  ralMailAdr  = 655;         { Please enter your mailing address (3 lines): }
  ralMGroups  = 656;                                      { Message groups: }
  ralNoMailI  = 657;            { No mailing address information on record! }
  ralMAListed = 658;           { Your mailing address is listed as follows: }
  ralChangeMA = 659;                          { Change your mailing address }
  ralOriginal = 660;                                             { Original }
  ralEnterThr = 661;                                         { Enter thread }
  ralInternet = 662;                                             { Internet }
  ralNewsGrp  = 663;                                            { Newsgroup }
  ralSorNoVw  = 664; { Sorry, this file is not currently available for view }
  ralScanAll  = 665;            { Mailbox scan will check ALL message areas }
  ralScanSel  = 666;          { Mailbox scan will check ONLY SELECTED areas }
  ralInvInter = 667;    { That is not a valid Internet address. Try again.. }
  ralFilesTag = 668;             { You have files tagged! Disconnect anyway }
  ralScanning = 669;                     { Scanning messages, please wait.. }
  ralCurTeleC = 670;                 { You are currently in teleconference: }
  ralPressEsc = 671; {Press ESC or CTRL-X for help, or start typing to chat.}
  ralTimeCurS = 672; { Time limit for your current session is up! Please .. }

  { EleBBS enhancements }
  ralNoConnect= 673;                              { Unable to connect to %s }
  ralConnIRC  = 674;                                     { Connecting to %s }
  ralIrcNoAcc = 675;                           { Server refused information }
  ralAskirc   = 676;                         { Connect to which IRC server: }
  ralNotOnChan= 677;                          { *** You're not on a channel }
  ralChanPref = 678;                                                 { [%s] }
  ralUserPref = 679;                                                 { (%s) }
  ralChanDeny = 680;     { Your sysop has forbidden access to this channel! }
  ralIrcDiscon= 681;                             { *** Disconnected from %s }
  ralWlcmSubj = 682;                                    { Welcome to EleBBS }
  ralMoreTVEK = 683;      {  YN=TVEK More(Y/n/=/(T)ag/(V)iew/(E)dit/S(k)ip? }
  ralUnlimited= 684;                                            { Unlimited }
  ralAskIrcNick=685;                        { Please enter nickname to use: }
  ralDDMMYYYY = 686;                                           { DD-MM-YYYY }
  ralMMDDYYYY = 687;                                           { MM-DD-YYYY }
  ralYYYYMMDD = 688;                                           { YYYY-MM-DD }
  ralDDMmmYYYY= 689;                                          { DD-Mmm-YYYY }
  ralDccChat  = 690;                   { Incoming DCC chat request, denying }
  ralDccSend  = 691;{ %s tries to send %s (%s bytes). Use /DCC GET %s to start }
  ralMaxDccs  = 692;      { Maximum number of DCC sessions reached, ignored }
  ralDccDone  = 693;             { DCC transfer of %s finished successfully }
  ralDccAbort = 694;                           { DCC transfer of %s aborted }
  ralDccNoSuch= 695;                                  { No such DCC session }
  ralDccStatus= 696;                     { File: %s from %s, bytes left: %s }
  ralDccConn  = 697;                          { Connecting to %s, to get %s }
  ralDccDling = 698;                      { Connected to %s, downloading %s }
  ralDccNoConn= 699;                       { Unable to connect to %s for %s }
  ralDccHdr   = 700;                      { Nick      State   %    filename }
  ralDccWait  = 701;                                              { Waiting }
  ralDccGetting=702;                                          { Downloading }
  ralDccWarn  = 703;{ Warning! DCC sessions are active, quitting will abort. Continue? }
  ralDccUnk   = 704;                                  { Unknown DCC command }
  ralDccEnable= 705;                                 { DCC sessions enabled }

  ralDccDisable=706;                                { DCC sessions disabled }
  ralDccNoDcc = 707;           { Your sysop has disabled DCC on this client }
  ralNetSend  = 708;      { Node is not know. Attempt to send anyway (y/N)? }
  ralAskTelnet= 709;                        { Connect to which telnet site: }
  ralTelConn  = 710;                                     { Connecting to %s }
  ralEdit1    = 711;                                             { I Ed(i)t }
  ralEdit2    = 712;                                                 { Edit }
  ralEditting = 713;                                  { Editting message in }
  ralHasEdit  = 714;            { Message has been editted by "%1" on %2 %3 }
  ralForumGrp = 715;                                                { Forum }
